import 'package:flutter/material.dart';

enum AchievementCategory { power, consistency, funny, wholesome, secret }

class Achievement {
  final String id;
  final String title;
  final String description;
  final IconData icon;
  final AchievementCategory category;
  final bool isSecret;

  const Achievement({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.category,
    this.isSecret = false,
  });
}

const List<Achievement> allAchievements = [
  // Power & Weight (12)
  Achievement(
    id: 'human_forklift',
    title: 'Human Forklift',
    description: 'Lift a total of 10,000kg across your history.',
    icon: Icons.unarchive,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'the_atlas',
    title: 'The Atlas',
    description: 'Reach 100,000kg (100 tons) lifetime volume.',
    icon: Icons.public,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'space_elevator',
    title: 'Space Elevator',
    description: 'Reach 500,000kg lifetime volume.',
    icon: Icons.rocket_launch,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'small_moon',
    title: 'Small Moon',
    description: 'Reach 1,000,000kg lifetime volume.',
    icon: Icons.brightness_2,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'shark_wrangler',
    title: 'Shark Wrangler',
    description: 'Lift the equivalent of a Great White Shark (1,100kg) in one go.',
    icon: Icons.scuba_diving,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'blue_whale',
    title: 'Blue Whale',
    description: 'Single session volume exceeds 15,000kg.',
    icon: Icons.water,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'moving_day',
    title: 'Moving Day',
    description: 'Lift a total of 50,000kg across your history.',
    icon: Icons.local_shipping,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'the_100_club',
    title: 'The 100 Club',
    description: 'Lift 100kg or more in a single exercise.',
    icon: Icons.fitness_center,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'ton_up',
    title: 'Ton-Up',
    description: 'Log 5 different exercises with 100kg+ in your history.',
    icon: Icons.layers,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'gravitys_enemy',
    title: 'Gravity\'s Enemy',
    description: 'Lift over 5,000kg in a single workout.',
    icon: Icons.public_off,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'plate_collector',
    title: 'Plate Collector',
    description: 'Perform 10 sets of 20kg+ in a single workout.',
    icon: Icons.view_comfortable,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'form_focus',
    title: 'Form Focus',
    description: 'Every exercise in a session is under 10kg.',
    icon: Icons.self_improvement,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'power_hour',
    title: 'Power Hour',
    description: 'Lift >3,000kg in under 60 minutes.',
    icon: Icons.speed,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'efficiency_expert',
    title: 'Efficiency Expert',
    description: 'Complete 5+ exercises in under 30 minutes.',
    icon: Icons.bolt,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'double_time',
    title: 'Double Time',
    description: 'Increase volume and decrease duration vs last workout.',
    icon: Icons.trending_up,
    category: AchievementCategory.power,
  ),

  // Consistency (11)
  Achievement(
    id: 'early_bird',
    title: 'Early Bird',
    description: 'Finish a workout before 7:00 AM.',
    icon: Icons.wb_sunny,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'night_owl',
    title: 'Night Owl',
    description: 'Finish a workout after 10:00 PM.',
    icon: Icons.nightlight_round,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'heavy_sleeper',
    title: 'Heavy Sleeper',
    description: 'Lift >2,000kg after 11:00 PM.',
    icon: Icons.bedtime,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'weekend_warrior',
    title: 'Weekend Warrior',
    description: 'Workout on both Saturday and Sunday in one week.',
    icon: Icons.date_range,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'unstoppable',
    title: 'Unstoppable',
    description: 'Maintain a 3-workout gap streak.',
    icon: Icons.local_fire_department,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'iron_will',
    title: 'Iron Will',
    description: 'Maintain a 10-workout gap streak.',
    icon: Icons.shield,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'immortal',
    title: 'Immortal',
    description: 'Maintain a 30-workout gap streak.',
    icon: Icons.all_inclusive,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'monday_motivator',
    title: 'Monday Motivator',
    description: 'Workout 4 Mondays in a row.',
    icon: Icons.calendar_today,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'monthly_master',
    title: 'Monthly Master',
    description: 'Log 20+ workouts in a single month.',
    icon: Icons.stars,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'monthly_legend',
    title: 'Monthly Legend',
    description: 'Log a workout on at least 26 days in a single month.',
    icon: Icons.calendar_month,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'double_down',
    title: 'Double Down',
    description: 'Log two separate workouts in a single day.',
    icon: Icons.exposure_plus_2,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'clockwork',
    title: 'Clockwork',
    description: '3 consecutive workouts with near-identical durations.',
    icon: Icons.history,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'lunch_break',
    title: 'Lunch Break',
    description: 'Workout entirely between 12:00 PM and 1:30 PM.',
    icon: Icons.lunch_dining,
    category: AchievementCategory.consistency,
  ),

  // Funny & Nice (10)
  Achievement(
    id: 'the_quickie',
    title: 'The Quickie',
    description: 'Do 3+ exercises in under 20 minutes.',
    icon: Icons.timer_3,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'is_this_a_marathon',
    title: 'Is This a Marathon?',
    description: 'Workout for more than 2 hours.',
    icon: Icons.directions_run,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'social_butterfly',
    title: 'Social Butterfly',
    description: 'Workout at 3 different locations.',
    icon: Icons.map,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'globetrotter',
    title: 'Globetrotter',
    description: 'Workout at 10 different locations.',
    icon: Icons.public,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'rest_day_rebel',
    title: 'Rest Day Rebel',
    description: 'Train on a recovery day.',
    icon: Icons.bolt,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'named_and_shamed',
    title: 'Named & Shamed',
    description: 'Give custom titles to 20 different workouts.',
    icon: Icons.label,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'the_sculptor',
    title: 'The Sculptor',
    description: 'Update your body weight 10 times.',
    icon: Icons.monitor_weight,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'correctionist',
    title: 'Correctionist',
    description: 'Manually override calorie count 5 times.',
    icon: Icons.edit_note,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'mathematical',
    title: 'Mathematical',
    description: 'Total volume is exactly divisible by 100.',
    icon: Icons.functions,
    category: AchievementCategory.funny,
  ),
  Achievement(
    id: 'the_tourist',
    title: 'The Tourist',
    description: 'Auto-detect location at a new spot.',
    icon: Icons.explore,
    category: AchievementCategory.funny,
  ),

  // Wholesome (10)
  Achievement(
    id: 'first_step',
    title: 'First Step',
    description: 'Complete your first workout!',
    icon: Icons.celebration,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'new_leaf',
    title: 'New Leaf',
    description: 'Workout on the 1st day of a month.',
    icon: Icons.eco,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'consistency_king',
    title: 'Consistency King',
    description: 'Train every day for a full week.',
    icon: Icons.workspace_premium,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'slow_and_steady',
    title: 'Slow & Steady',
    description: 'Increase volume by 1-5% over your last workout.',
    icon: Icons.trending_up,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'silver_anniversary',
    title: 'Silver Anniversary',
    description: 'Log your 25th workout.',
    icon: Icons.workspace_premium,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'gold_anniversary',
    title: 'Gold Anniversary',
    description: 'Log your 50th workout.',
    icon: Icons.military_tech,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'centurion',
    title: 'Centurion',
    description: 'Log your 100th workout.',
    icon: Icons.history_edu,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'the_archivist',
    title: 'The Archivist',
    description: 'View a workout from over 1 year ago.',
    icon: Icons.auto_stories,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'steady_gains',
    title: 'Steady Gains',
    description: 'Increase total volume 5 sessions in a row.',
    icon: Icons.assessment,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'self_care_sunday',
    title: 'Self-Care Sunday',
    description: 'Workout on 4 Sundays in a row.',
    icon: Icons.favorite,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'shift_work',
    title: 'Shift Work',
    description: 'Spend a total of 8 hours working out.',
    icon: Icons.work,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'round_the_clock',
    title: 'Round the Clock',
    description: 'Spend a total of 24 hours lifetime duration.',
    icon: Icons.access_time_filled,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'the_century_club',
    title: 'The Century Club',
    description: 'Spend 100 hours lifetime in the gym.',
    icon: Icons.workspace_premium,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'deep_space',
    title: 'Deep Space',
    description: 'Spend 500 hours lifetime duration.',
    icon: Icons.rocket,
    category: AchievementCategory.wholesome,
  ),

  // Secret (7)
  Achievement(
    id: 'beast_mode',
    title: 'Beast Mode',
    description: 'Lift more than 10x your bodyweight in total volume.',
    icon: Icons.pets,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'lightweight_baby',
    title: 'Lightweight Baby!',
    description: 'Lift exactly the same volume two sessions in a row.',
    icon: Icons.repeat,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'devils_lift',
    title: 'Devil\'s Lift',
    description: 'Lift a demonic volume (666...).',
    icon: Icons.whatshot,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'lucky_lift',
    title: 'Lucky Lift',
    description: 'Lift a lucky volume (777...).',
    icon: Icons.auto_awesome,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'the_answer',
    title: 'The Answer',
    description: 'The answer to life, universe, and everything (42...).',
    icon: Icons.help_center,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'ghost',
    title: 'Ghost',
    description: 'Workout for 45 minutes with 0 volume.',
    icon: Icons.visibility_off,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'insomniac',
    title: 'Insomniac',
    description: 'Start a workout between 2:00 AM and 4:00 AM.',
    icon: Icons.dark_mode,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'after_hours',
    title: 'After Hours',
    description: 'Workout that spans across midnight.',
    icon: Icons.night_shelter,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'hibernation',
    title: 'Hibernation',
    description: 'A single workout duration exceeding 12 hours.',
    icon: Icons.airline_seat_individual_suite,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  // Templates (3)
  Achievement(
    id: 'the_planner',
    title: 'The Planner',
    description: 'Create your first workout template.',
    icon: Icons.assignment,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'architect_of_gains',
    title: 'Architect of Gains',
    description: 'Have 5 active workout templates at the same time.',
    icon: Icons.architecture,
    category: AchievementCategory.wholesome,
  ),
  Achievement(
    id: 'grand_designer',
    title: 'Grand Designer',
    description: 'Amass 10 active workout templates at the same time.',
    icon: Icons.draw,
    category: AchievementCategory.wholesome,
  ),
  // Cardio & Mixed (3)
  Achievement(
    id: 'road_warrior',
    title: 'Road Warrior',
    description: 'Reach 50km total lifetime cardio distance.',
    icon: Icons.add_road,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'pure_hearts',
    title: 'Pure Hearts',
    description: 'Complete a workout consisting only of Cardio exercises.',
    icon: Icons.favorite,
    category: AchievementCategory.consistency,
  ),
  Achievement(
    id: 'the_hybrid',
    title: 'The Hybrid',
    description: 'Complete a workout with both Gym and Cardio exercises.',
    icon: Icons.layers,
    category: AchievementCategory.wholesome,
  ),
  // Secret Leg Days (2)
  Achievement(
    id: 'friends_dont_let_friends',
    title: 'Friends Don\'t Let Friends...',
    description: '...skip Leg Day. Logged your first leg-focused workout.',
    icon: Icons.accessibility_new,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  Achievement(
    id: 'chicken_leg_cure',
    title: 'Chicken Leg Cure',
    description: 'Logged 10 separate leg-focused workouts.',
    icon: Icons.fitness_center,
    category: AchievementCategory.secret,
    isSecret: true,
  ),
  // More Cardio (4)
  Achievement(
    id: 'forest_gump',
    title: 'Forest Gump',
    description: 'Complete a single cardio set longer than 60 minutes.',
    icon: Icons.timer,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'speed_demon',
    title: 'Speed Demon',
    description: 'Complete 5km in under 30 minutes in a single set.',
    icon: Icons.speed,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'marathon_man',
    title: 'Marathon Man',
    description: 'Cover more than 42.2km in a single session.',
    icon: Icons.directions_run,
    category: AchievementCategory.power,
  ),
  Achievement(
    id: 'cross_country',
    title: 'Cross Country',
    description: 'Reach 500km total lifetime cardio distance.',
    icon: Icons.map,
    category: AchievementCategory.power,
  ),
];
